### ISSUE TITLE
Can't open file with path containing '#'

### ISSUE THREAD

**Issue by cagechi** [obaland/vfiler.vim#10]
OS: Windows11
NVIM: v0.8.3
![スクリーンショット 2023-03-13 215355](https://user-images.githubusercontent.com/14066785/224708705-efc507d1-8a06-4c0f-bed8-9910f16653ab.png)

**Comment by obaland** [comment]
Thank you for contacting me.
Please wait a moment while I check the cause of the problem.

**Comment by obaland** [comment]
@cagechi 
Fixed to support special characters. (https://github.com/obaland/vfiler.vim/commit/17d673ce91c5779859bfa0453696717ccd149292)
Please take a moment to check it.

**Comment by cagechi** [comment]
I checked it, thanks for the fix!

**Comment by obaland** [comment]
@cagechi 
I will close it.
Please contact us if you have any problems.
