### ISSUE TITLE
can not display the git status in column?

### ISSUE THREAD

**Issue by lee-shun** [obaland/vfiler.vim#13]
Hello! Thank you for this great plugin!

I use lazy.nvim as the plugins manager and I have the following configs: 
```lua
return {
	"obaland/vfiler.vim",
	keys = {
		{ "<leader>t", "<cmd>VFiler<cr>", desc = "Open vfiler" },
	},
    cmd = {"VFiler"},
    dependencies = {"obaland/vfiler-column-devicons"},
	config = function(_, opts)
		local action = require("vfiler/action")
		-- following options are the default
        require'vfiler/config'.clear_mappings()
		require("vfiler/config").setup({
			options = {
				auto_cd = true,
				auto_resize = true,
				columns = "indent,devicons,name,git,time,mode,size",
				find_file = true,
				header = true,
				keep = true,
				listed = true,
				name = "",
				session = "buffer",
				show_hidden_files = true,
				sort = "name",
				layout = "left",
				width = 80,
				height = 20,
				new = false,
				quit = true,
				row = 0,
				col = 0,
				blend = 0,
				border = "rounded",
				zindex = 200,
				git = {
					enabled = true,
					ignored = true,
					untracked = true,
				},
				preview = {
					layout = "floating",
					width = 0,
					height = 0,
				},
			},
			mappings = {
				["."] = action.toggle_show_hidden,
				["<BS>"] = action.change_to_parent,
				["<C-l>"] = action.reload,
				["<C-p>"] = action.toggle_auto_preview,
				["<C-r>"] = action.sync_with_current_filer,
				["<C-s>"] = action.toggle_sort,
				["<CR>"] = action.open,
				["K"] = function(vfiler, context, view)
					action.toggle_select(vfiler, context, view)
					action.move_cursor_up(vfiler, context, view)
				end,
				["J"] = function(vfiler, context, view)
					action.toggle_select(vfiler, context, view)
					action.move_cursor_down(vfiler, context, view)
				end,
				["<Tab>"] = action.switch_to_filer,
				["~"] = action.jump_to_home,
				["*"] = action.toggle_select_all,
				["\\"] = action.jump_to_root,
				["cc"] = action.copy_to_filer,
				["dd"] = action.delete,
				["gg"] = action.move_cursor_top,
				["b"] = action.list_bookmark,
				["h"] = action.close_tree_or_cd,
				["j"] = action.loop_cursor_down,
				["k"] = action.loop_cursor_up,
				["l"] = action.open_tree,
				["M"] = action.move_to_filer,
				["P"] = action.toggle_preview,
				["q"] = action.quit,
				["r"] = action.rename,
				["s"] = action.open_by_split,
				["t"] = action.open_by_tabpage,
				["v"] = action.open_by_vsplit,
				["e"] = action.execute_file,
				["yp"] = action.yank_path,
				["B"] = action.add_bookmark,
				["yy"] = action.copy,
				["D"] = action.delete,
				["G"] = action.move_cursor_bottom,
				-- ["J"] = action.jump_to_directory,
				["A"] = action.new_directory,
				["L"] = action.switch_to_drive,
				["x"] = action.move,
				["a"] = action.new_file,
				["p"] = action.paste,
				["S"] = action.change_sort,
				["U"] = action.clear_selected_all,
				["yn"] = action.yank_name,
			},
		})
	end,
}

```
but I can not have the git status displaying in the column:
![image](https://user-images.githubusercontent.com/46647235/229672547-e14e3a19-fd1f-4ec1-8589-46885fb585e1.png)

The expected result should be:
![image](https://user-images.githubusercontent.com/46647235/229672838-1d39d68b-c29f-43a7-a16e-fe569851495e.png)

**Comment by obaland** [comment]
Thank you very much for your report.

I just fixed the relevant part.
Could you please update to the latest version and let us know the result, so that we can possibly improve it?

Best regards.

**Comment by lee-shun** [comment]
Just tested the new version, and it works! Thank you so much! :+1: 

Now I want to have a command something like "VFilerToggle", is there any hack to do that?

**Comment by obaland** [comment]
Thanks for the confirmation.
Glad to see it works.

I am interested in the `Toggle`, but have not yet supported it because I did not envision it in my usage.
Would `NERDTreeToggle` be a good reference for a working specification?
If you have any other reference, I would appreciate it if you could let me know.

I are assuming that the direction of the response is to add an option rather than a command. 
Any input in this area would be appreciated as well.

Best regards.

**Comment by lee-shun** [comment]
Thank you! I would recommend the [nvim-tree](https://github.com/nvim-tree/nvim-tree.lua).
It provides the NvimTreeToggle command.

**Comment by obaland** [comment]
@lee-shun 
Thank you for your patience.
Although not officially documented, the `toggle` option has been implemented. (175275b5e71201fd858d7fb1ea094bd513a0d60b)
Specify it in `options`.
```lua
require("vfiler/config").setup({
  options = {
    ... 
    toggle = true,
    ...
  },
})
```
Please try it.
I am looking forward to your feedback.

Best regards.

**Comment by lee-shun** [comment]
Great! I just tested this feature! It works perfectly.
Thank you so much for this great plugin. Love it!
