### ISSUE TITLE
meaningless symbols when searching in the vfiler

### ISSUE THREAD

**Issue by lee-shun** [obaland/vfiler.vim#14]
I want to search some file in the open vfiler tree, but after I pressed "/", there are many meaningless symbols...

before:
![image](https://user-images.githubusercontent.com/46647235/229809570-8ee2a5fc-241a-4e74-b559-bd4e1de725fd.png)

after searching:

![image](https://user-images.githubusercontent.com/46647235/229809761-a3b2a01d-3661-4884-af2b-b7958adc571b.png)

**Comment by obaland** [comment]
Thanks for the report.
These symbols are for syntax highlighting and should normally be sealed.
What plugin are you using for your search?

**Comment by lee-shun** [comment]
Oh, nothing special, just the bulid-in search "/". 
The popup menu is provided by [noice.nvim](https://github.com/folke/noice.nvim)

**Comment by obaland** [comment]
Thank you very much for the information you have provided.
First, I will investigate whether similar symptoms occur based on the tips you provided.
I will report back to you if we make any progress.

**Comment by lee-shun** [comment]
Thank you for your quick reply!

**Comment by obaland** [comment]
It seems that the `conceallevel` option is changed to `0` at the `CmdlineEnter` event in `noice.nvim`.
Please give us some time to think about how to handle this.

**Comment by obaland** [comment]
Sorry. I have considered it,
A simple workaround is difficult because the `noice.nvim` side is changing options on events.

I can suggest a hack to disable `noice.nvim` when using `vfiler`.
The following can be written in the configuration file to disable it for the `vfiler`.

```lua
vim.api.nvim_create_autocmd({'BufEnter'}, {
  pattern = '*vfiler*',
  callback = function(event)
    local ok, noice = pcall(require, 'noice')
      if ok then
        noice.disable()
      end
  end,
})

vim.api.nvim_create_autocmd({'BufLeave'}, {
  pattern = '*vfiler*',
  callback = function(event)
    local ok, noice = pcall(require, 'noice')
    if ok then
      noice.enable()
    end
  end,
})
```

This is the only way I can think of at the moment,
I will report back if I come up with another strange idea.

**Comment by lee-shun** [comment]
Humm, thank you for your advice!

However,  I like the floating input provided by `noice.nvim` when creating the new file .etc. So I would not sacrifice this feature for the search.

I think I should get used to the file tree without searching :)

**Comment by lee-shun** [comment]
So, what would be your suggestion for the searching method in vfiler? Does vfiler provide the searching method?

**Comment by obaland** [comment]
Thanks for your input.
Hmmm, in`'vfiler.vim` the search is left to the editor function, so there are no plans to provide it.

I will consider two ideas.
1. Minimize the number of conceal characters as necessary to make it as unattractive as possible.
2. Syntax highlighting support independent of the `conceallevel` option.

First, I will tentatively consider `1`.
Thank you for your continued support.

Best regards.

**Comment by lee-shun** [comment]
Great! you are my hero:)

**Comment by obaland** [comment]
Thank you for your patience.

After much consideration. I have implemented this as a patch to mitigate the problem.
https://github.com/obaland/vfiler-patch-noice.nvim
Please try it and let us know what you think.

Best regards

**Comment by lee-shun** [comment]
Just tested it, and it works great! Thank you for your all the way support! :)

By the way, there is a little issue in the "README.md" of that patch repo:

in the "Installation" section:
```lua
require'vfiler/patches/noive'.setup()
-- ...
require('vfiler').start()
```
which should be:

```lua
require'vfiler/patches/noice'.setup()
-- ...
require('vfiler').start()
```

**Comment by obaland** [comment]
My apologies. :-<
The typo has been corrected.

**Comment by lee-shun** [comment]
cheers！
