### ISSUE TITLE
feature request: a method that can tell if current item is a directory

### ISSUE THREAD

**Issue by lee-shun** [obaland/vfiler.vim#15]
Hello, I have a new idea I can somehow use the `l` key to open tree and open file without changing current directory. Then there is no need to move my finger from `l` to `<CR>` to open the file...

so in the "mapping" configuration, I may need something like below:

```lua
{
mapping = {
["l"] = function(vfiler, context, view)
if action.is_directory(vfiler, context, view) then
return action.open_tree(vfiler, context, view)
else
return action.open_file(vfiler, context, view)`
end
}
}
```

Yes, I need this `action.is_directory(vfiler, context, view)` API...

**Comment by obaland** [comment]
That is a great idea.

Sorry for the lack of clarity, as the documentation is not yet complete.
Actually, it is possible to achieve this in the current situation.
Here is a concrete example.

```lua
local action = require('vfiler/action')
require('vfiler/config').setup({
  mappings = {
    ['l'] = function(vfiler, context, view)
      local item = view:get_item()
      if item.type == 'directory' then
        action.open_tree(vfiler, context, view)
      else
        action.open(vfiler, context, view)
      end
    end,
  },
})
```

If it is still needed as `action.is_drectory`, I will consider implementing it as a utility action, so your feedback would be appreciated.

Best regards.

**Comment by lee-shun** [comment]
Great! thank you for your help. I think there is no need to implement `action.is_drectory` right now! Cheers!
