### ISSUE TITLE
Feature Request: Add option to ignore specific windows when opening file (with buftype/filetype)

### ISSUE THREAD

**Issue by annenpolka** [obaland/vfiler.vim#3]
![open_with_incline](https://user-images.githubusercontent.com/56289203/166106638-77b641c0-8938-4ebe-9cf6-6d6643ffe259.png)

When using with [b0o/incline.nvim](https://github.com/b0o/incline.nvim), vfiler detects incline's window and treats it as a choice.
It's so helpful if there is an option to ignore specific types windows.

**Comment by obaland** [comment]
Thanks for the request.
I understand what you are asking.
We will consider how to do it. Please give us a few minutes of your time.

**Comment by obaland** [comment]
Thank you for your patience.
In https://github.com/obaland/vfiler.vim/commit/da64afaee29ba4a552473d33b3b70c2237d7d021, The requested functionality is now supported in the action module configurations, allowing you to set an arbitrary hook function that can filter windows.

Below is an example configuration for [b0o/incline.nvim](https://github.com/b0o/incline.nvim).
```Lua
require('vfiler/action').setup {
  hook = {
    filter_choose_window = function(winids)
      return vim.tbl_filter(function(winid)
        local buffer = vim.api.nvim_win_get_buf(winid)
        return vim.api.nvim_buf_get_option(buffer, 'filetype') ~= 'incline'
      end, winids)
    end,
  },
}
```

I would appreciate your evaluation.

**Comment by annenpolka** [comment]
@obaland This looks clean and flexible!
 Confirmed working as I suppose, thank you for your great work:+1:
