### ISSUE TITLE
Can't open UNC path

### ISSUE THREAD

**Issue by cagechi** [obaland/vfiler.vim#32]
When I try to open a UNC path, following error is thrown.

ex1. require("vfiler").start("//COMPUTERNAME/FOLDERNAME")
ex2. require("vfiler").start("\\\\COMPUTERNAME\\FOLDERNAME")

```
E5108: Error executing lua ...ocal/nvim-data/lazy/vfiler.vim/lua/vfiler/items/item.lua:72: attempt to index local 'stat' (a nil value)
stack traceback:
	...ocal/nvim-data/lazy/vfiler.vim/lua/vfiler/items/item.lua:72: in function 'new'
	...Local/nvim-data/lazy/vfiler.vim/lua/vfiler/libs/core.lua:22: in function 'inherit'
	...nvim-data/lazy/vfiler.vim/lua/vfiler/items/directory.lua:33: in function 'new'
	...a/Local/nvim-data/lazy/vfiler.vim/lua/vfiler/context.lua:297: in function 'switch'
	...ta/Local/nvim-data/lazy/vfiler.vim/lua/vfiler/vfiler.lua:275: in function 'start'
	...1/AppData/Local/nvim-data/lazy/vfiler.vim/lua/vfiler.lua:32: in function 'start'
	[string ":lua"]:1: in main chunk
```

OS: Windows10
NVIM: v0.9.5
vfiler.vim: ed2c4a7

**Comment by obaland** [comment]
Thanks for the report.
This is most likely a bug and will be investigated and corrected.
Sorry, please give us a little time to fix it.

**Comment by obaland** [comment]
@cagechi 
Fixed to support UNC path. (1328b9f8ea4c9341a860597311dc817605c45750)
Please check it.

**Comment by cagechi** [comment]
@obaland 

Thank you for update.
I checked it.

require("vfiler").start("\\\\COMPUTERNAME\\FOLDERNAME")  is good
but require("vfiler").start("//COMPUTERNAME/FOLDERNAME") is failed.
Can I use slash in UNC path on windows ?

vfiler.vim: 1328b9f

**Comment by obaland** [comment]
@cagechi 
Sorry. There was a misunderstanding on my part.
Both have been corrected to work.
610954af99482d5a87a880f27c01c5d2acc5c3fc

**Comment by cagechi** [comment]
Thank you for your response.

require("vfiler").start("//COMPUTERNAME/FOLDERNAME") is now good.
but the following error occurs when selecting a directory after starting the Filer.
Sorry for the lack of confirmation.

`
jobwait table: 0x01d69f7db990 -1 .../lazy/vfiler.vim/lua/vfiler/libs/async/jobs/job_nvim.lua:6: fatal: cannot change to '//COMPUTERNAME/FOLDERNAME'//COMPUTERNAME/FOLDERNAME'��L�̌��݂̃f�B���N�g���� CMD.EXE ��J�n���܂����BUNC �p�X�̓T�|�[�g����܂���BWindows �f�B���N�g�������Ŏg�p���܂��Bfatal: not a git repository (or any of the parent directories): .git': Invalid argument
stack traceback:
^I[C]: in function 'error'
^I.../lazy/vfiler.vim/lua/vfiler/libs/async/jobs/job_nvim.lua:6: in function 'on_error'
^I.../lazy/vfiler.vim/lua/vfiler/libs/async/jobs/job_nvim.lua:23: in function <.../lazy/vfiler.vim/lua/vfiler/libs/async/jobs/job_nvim.lua:20>
^I[C]: in function 'jobwait'
^I.../lazy/vfiler.vim/lua/vfiler/libs/async/jobs/job_nvim.lua:67: in function 'wait'
^I...a/Local/nvim-data/lazy/vfiler.vim/lua/vfiler/context.lua:302: in function 'switch'
^I...im-data/lazy/vfiler.vim/lua/vfiler/actions/utilities.lua:167: in function 'cd'
^I...im-data/lazy/vfiler.vim/lua/vfiler/actions/utilities.lua:148: in function 'edit_file'
^I...im-data/lazy/vfiler.vim/lua/vfiler/actions/utilities.lua:209: in function 'open_file'
^I...al/nvim-data/lazy/vfiler.vim/lua/vfiler/actions/open.lua:7: in function 'action'
^I...ta/Local/nvim-data/lazy/vfiler.vim/lua/vfiler/vfiler.lua:214: in function 'do_action'
^I...ta/Local/nvim-data/lazy/vfiler.vim/lua/vfiler/vfiler.lua:195: in function '_do_action'
^I[string ":lua"]:1: in main chunk
`


vfiler.vim: 610954a

**Comment by obaland** [comment]
@cagechi 
Thanks for the confirmation.
There seems to be a condition that causes the error. I will look into it. Sorry for the inconvenience, but please give us a little more time.

**Comment by obaland** [comment]
@cagechi
Fixed. Your confirmation would be appreciated. 
98d715693ff326fe3b43adb49ff372eb03f9b3ad

**Comment by cagechi** [comment]
@obaland Thank you!
It's working as expected.

**Comment by obaland** [comment]
Fix is complete and will be closed.
