### ISSUE TITLE
Focus by file and toggle select.

### ISSUE THREAD

**Issue by thevan96** [obaland/vfiler.vim#4]
How to focus the current file in vfiler?
![Peek 2022-06-07 20-11](https://user-images.githubusercontent.com/47932916/172388517-057db5b5-dc37-4fbf-945d-88c1709a7bae.gif)

Can you select by visual?

Currently, I'm using defx.nvim to explore tree

**Comment by obaland** [comment]
Thank you for your question.
The file selection action is assigned to the `<Space>` key by default.
```lua
['<Space>'] = function(vfiler, context, view)
  action.toggle_select(vfiler, context, view)
  action.move_cursor_down(vfiler, context, view)
end
```
Unfortunately, Do not support visual mode at this time.
I will consider supporting it if necessary.

**Comment by thevan96** [comment]
Your plugin is good, but it's not popular. Thank you.

**Comment by thevan96** [comment]
It means I'm currently open file init.vim. How to focus file init.vim inside vfiler.

![Peek 2022-06-08 09-50](https://user-images.githubusercontent.com/47932916/172521143-185d8376-2fde-4743-9d55-9436183d4be8.gif)

Config in defx.nvim like it.
```
nnoremap <silent><leader>F :Defx -search-recursive=`expand('%:p')`
      \ -resume
      \ -sort=extension:filename
      \ -columns=indent:indent:icon:mark:filename
      \ -show-ignored-files
      \ -listed<cr><C-w>=
```
Or :Explore of netrw

**Comment by obaland** [comment]
This is a confirmation of the question intent.
I want the filer to start with focus on the currently open file when it starts. Is this what you mean?

**Comment by thevan96** [comment]
I often open files with telescope/telescope, after focusing on tree explores if necessary to process with files/folder.
Focus currently open file if necessary, not start.
Like :Explore of netrw

Another problem, was when I quit, the struct folder expands reset. How to keep the folder structure previously opened? Maybe need to toggle VFiler?

**Comment by obaland** [comment]
Thank you for your input.
I now have a much better understanding of the usage assumptions.
Please let me explore including `toggle` with reference to `netrw`.
Please take some time for prototyping and let us discuss it here when the prototype is ready.

**Comment by obaland** [comment]
I would like to ask for your opinion.
I am thinking of adding `find-file` as an option to recursively find the current buffer and change the cursor when vfiler is started.
This option is a boolean option and does not ask for a path to be specified.
I was referring to the behavior of the [:NvimTreeFindFile](https://github.com/kyazdani42/nvim-tree.lua/blob/master/doc/nvim-tree-lua.txt) command in [nvim-tree.lua](https://github.com/kyazdani42/nvim-tree.lua).

The reason for this is that most of the time when using such an option, the current buffer name is specified, so we wanted to make it as simple as possible.

So, please let me know if the above direction is OK, or if it would still be better to allow the path to be specified arbitrarily, for reference.

**Comment by thevan96** [comment]
Thank you for your support.

At the suggestion above, I installed nvim-tree, the command :NvimTreeFindFile is also the same thing that I asked this to be created
I think this solution is simpler than defx.nvim, but it makes sense. Keep it as simple as possible.

You can implement a command similar to the above, maybe  :VFilerFindFile?

**Comment by obaland** [comment]
Thank you for your answer.
I would like to implement the `VFiler` command only if possible, so I am thinking of implementing it as an option.
If it is a configuration, I would like to use
```lua
require('vfiler/config').setup {
  options = {
    --
    find_file = true,
    --
  },
}
```
If it is invoked from the command
```vim
VFiler -find-file
```
Please give me some more time to implement this.
Thank you.

**Comment by obaland** [comment]
The `find_file` option has been implemented at https://github.com/obaland/vfiler.vim/commit/3a7a5d727df8a4099ededa969747582667ebbb29.
As announced, please try one of the following methods.
```lua
require('vfiler/config').setup {
  options = {
    --
    find_file = true,
    --
  },
}
```
or
```vim
VFiler -find-file
```
I look forward to hearing from you.

**Comment by thevan96** [comment]
It works, you can update the document.
I appreciate your support

**Comment by obaland** [comment]
Added to the document.
Thank you very much for your time.
I look forward to working with you again.
