### ISSUE TITLE
[Question] ヘルプでデフォルトマップ一覧の表示

### ISSUE THREAD

**Issue by kohey821** [obaland/vfiler.vim#8]
`:help xxx`でデフォルトマップの一覧を参照することは可能でしょうか？

**Comment by obaland** [comment]
問い合わせありがとうございます。
[vim-plug](https://github.com/junegunn/vim-plug) 等のプラグイン管理で、ヘルプファイルのタグが生成されていれば、
```:help vfiler-default-configurations```
で、一覧形式ではないですが、デフォルトマップを参照することはできます。

もし、意図と異なるようでしたら対応を検討しますので、
他のプラグイン事例など、要望に対する情報提供いただけると助かります。

**Comment by kohey821** [comment]
ありがとうございます！

すみません、`:help vfilter.txt`で一覧されているのを見落としておりました。
